name: tflite_style_transfer
description: Tensorflow Lite Style Transfer Model.
version: 0.1.1
repository: https://github.com/luiscib3r/tflite_style_transfer

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: tflite_style_transfer_android
      ios:
        default_package: tflite_style_transfer_ios

dependencies:
  flutter:
    sdk: flutter
  tflite_style_transfer_android: ^0.1.1
  tflite_style_transfer_ios: ^0.1.1
  tflite_style_transfer_platform_interface: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  plugin_platform_interface: ^2.0.0
  very_good_analysis: ^3.0.1
